name: auto-labeler

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        id: labeler
        uses: gofiber/multi-labeler@v0.2.0
        with:
          github-token: ${{ secrets.ISSUE_PR_TOKEN }}
          config-path: .github/labeler.yml
          config-repo: gofiber/fiber

