name: auto-labeler

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  auto-labeler:
    uses: gofiber/.github/.github/workflows/auto-labeler.yml@main
    secrets:
      github-token: ${{ secrets.ISSUE_PR_TOKEN }}
    with:
      config-path: .github/labeler.yml
      config-repository: gofiber/fiber
